SELECT
    PPNF.DISPLAY_NAME      AS "Nome Completo",
    PAPF.PERSON_NUMBER     AS "Número Pessoal",
    PAAM.ASSIGNMENT_NUMBER AS "Matrícula",
    TO_CHAR(PPOS.DATE_START,
    'DD/MM/YYYY')          AS "Data Admissão",
    PJ.NAME                AS "Cargo",
    CS.SALARY_AMOUNT       "Salário",
    ORG.ORGANIZATION_NAME  AS "Empresa",
    PPNF2.DISPLAY_NAME     AS "Gerente"
FROM
    PER_ALL_PEOPLE_F             PAPF,
    PER_PERSON_NAMES_F           PPNF,
    PER_PERSON_NAMES_F           PPNF2,
    PER_ALL_ASSIGNMENTS_M        PAAM,
    PER_PERIODS_OF_SERVICE       PPOS,
    CMP_SALARY                   CS,
    PER_JOBS                     PJ,
    PER_ASSIGNMENT_SUPERVISORS_F PASF,
    (
        SELECT
            HAOU.ORGANIZATION_ID AS ORGANIZATION_ID,
            XRV.REGISTERED_NAME  AS ORGANIZATION_NAME
        FROM
            HR_ALL_ORGANIZATION_UNITS_F HAOU,
            XLE_ENTITY_PROFILES         XEP,
            XLE_REGISTRATIONS_V         XRV
        WHERE
            XEP.LEGAL_ENTITY_ID = HAOU.LEGAL_ENTITY_ID
            AND XRV.LEGAL_ENTITY_ID = XEP.LEGAL_ENTITY_ID
            AND HAOU.EFFECTIVE_START_DATE = (
                SELECT
                    MAX(EFFECTIVE_START_DATE)
                FROM
                    HR_ALL_ORGANIZATION_UNITS_F
                WHERE
                    ORGANIZATION_ID = HAOU.ORGANIZATION_ID
            )
    )                            ORG
WHERE
    PPNF.PERSON_ID = PAPF.PERSON_ID
    AND PAPF.PERSON_NUMBER = NVL(:P_PERSON_NUMBER,
    PAPF.PERSON_NUMBER)
 -- filter papf
    AND PAPF.EFFECTIVE_START_DATE = (
        SELECT
            MAX(PAPF_INNER.EFFECTIVE_START_DATE)
        FROM
            PER_ALL_PEOPLE_F PAPF_INNER
        WHERE
            PAPF_INNER.PERSON_NUMBER = PAPF.PERSON_NUMBER
    )
 -- filter ppnf
    AND PPNF.NAME_TYPE = 'GLOBAL'
    AND PPNF.EFFECTIVE_START_DATE = (
        SELECT
            MAX(EFFECTIVE_START_DATE)
        FROM
            PER_PERSON_NAMES_F
        WHERE
            PERSON_ID = PPNF.PERSON_ID
            AND NAME_TYPE = PPNF.NAME_TYPE
    )
    AND PPNF.EFFECTIVE_END_DATE <> PPNF.EFFECTIVE_START_DATE
 -- filter paam
    AND PAAM.PERSON_ID = PAPF.PERSON_ID
    AND PAAM.WORK_TERMS_ASSIGNMENT_ID IS NOT NULL
    AND PAAM.ASSIGNMENT_TYPE = 'E'
    AND PAAM.ASSIGNMENT_STATUS_TYPE= 'ACTIVE'
    AND PAAM.EFFECTIVE_START_DATE= (
        SELECT
            MAX(EFFECTIVE_START_DATE)
        FROM
            PER_ALL_ASSIGNMENTS_M PAAM_INNER
        WHERE
            PAAM_INNER.PERSON_ID = PAPF.PERSON_ID
            AND PAAM_INNER.WORK_TERMS_ASSIGNMENT_ID IS NOT NULL
            AND PAAM_INNER.ASSIGNMENT_TYPE = PAAM.ASSIGNMENT_TYPE
            AND PAAM_INNER.ASSIGNMENT_STATUS_TYPE = PAAM.ASSIGNMENT_STATUS_TYPE
            AND PAAM_INNER.PRIMARY_FLAG = PAAM.PRIMARY_FLAG
    )
    AND PAAM.EFFECTIVE_END_DATE <> PAAM.EFFECTIVE_START_DATE
 -- filter cs
    AND CS.DATE_TO = (
        SELECT
            MAX(DATE_TO)
        FROM
            CMP_SALARY CS_INNER
        WHERE
            CS_INNER.ASSIGNMENT_ID = PAAM.ASSIGNMENT_ID
            AND CS_INNER.PERSON_ID = CS.PERSON_ID
    )
    AND CS.ASSIGNMENT_ID = PAAM.ASSIGNMENT_ID
    AND CS.PERSON_ID = PAAM.PERSON_ID
    AND CS.SALARY_APPROVED = 'Y'
 -- ppos
    AND PPOS.PERSON_ID = PAAM.PERSON_ID
    AND PPOS.PERIOD_OF_SERVICE_ID = PAAM.PERIOD_OF_SERVICE_ID
 --pj
    AND PJ.JOB_ID = PAAM.JOB_ID
 -- pasf
    AND PASF.ASSIGNMENT_ID = PAAM.ASSIGNMENT_ID
    AND PASF.EFFECTIVE_START_DATE = (
        SELECT
            MAX(EFFECTIVE_START_DATE)
        FROM
            PER_ASSIGNMENT_SUPERVISORS_F PASF_INNER
        WHERE
            PASF_INNER.ASSIGNMENT_ID = PAAM.ASSIGNMENT_ID
    )
    AND PPNF2.PERSON_ID = PASF.MANAGER_ID
    AND PPNF2.NAME_TYPE = 'GLOBAL'
 -- org
    AND ORG.ORGANIZATION_ID = PAAM.LEGAL_ENTITY_ID